name: Salus
main: Driesboy\Salus\Salus
version: 3.2.3
load: STARTUP
enable: STARTUP
author: Driesboy
api: [3.0.0-ALPHA5,3.0.0-ALPHA6,3.0.0-ALPHA7,3.0.0-ALPHA8,3.0.0-ALPHA9,3.0.0-ALPHA10,3.0.0]
commands:
      Salusanticheat:
           description: Shows SalusAntiCheat version
           aliases: ["SalusAntiCheat","AntiCheat","Salus"]
      Salus:
           description: Shows SalusAntiCheat version
           aliases: ["SalusAntiCheat","AntiCheat","Salus"]
permissions:
    legitop:
        description: "A permission."
        default: false
    Salus:
        description: "Allows to use all Salus features."
        default: false
        children:
            Salus.fly:
                description: "A permission."
                default: false
            Salus.glide:
                description: "A permission."
                default: false
            Salus.speed:
                description: "A permission."
                default: false
            Salus.noclip:
                description: "A permission."
                default: false
            Salus.reach:
                description: "A permission."
                default: false
            Salus.instantkill:
                description: "A permission."
                default: false
            Salus.killaura:
                description: "A permission."
                default: false
            Salus.regen:
                description: "A permission."
                default: false
            Salus.forcegamemode:
                description: "A permission."
                default: false
