name: Salus
main: Driesboy\Salus\Salus
version: 3.2.5
load: STARTUP
enable: STARTUP
author: Driesboy
api: [3.0.0-ALPHA1,3.0.0-ALPHA2,3.0.0-ALPHA3,3.0.0-ALPHA4,3.0.0-ALPHA5,3.0.0-ALPHA6,3.0.0-ALPHA7,3.0.0-ALPHA8,3.0.0-ALPHA9,3.0.0-ALPHA10,3.0.0]
commands:
      Salusanticheat:
           description: Shows SalusAntiCheat version
           aliases: ["SalusAntiCheat","AntiCheat","Salus"]
      salus:
           description: Shows SalusAntiCheat version
           aliases: ["SalusAntiCheat","AntiCheat","Salus"]
permissions:
    legitop:
        description: "A permission."
        default: false
    salus:
        description: "Allows to use all salus features."
        default: false
        children:
            rank.moderator:
                description: "Get notified when someone is hacking."
                default: op
            salus.fly:
                description: "A permission."
                default: false
            salus.glide:
                description: "A permission."
                default: false
            salus.speed:
                description: "A permission."
                default: false
            salus.noclip:
                description: "A permission."
                default: false
            salus.reach:
                description: "A permission."
                default: false
            salus.instantkill:
                description: "A permission."
                default: false
            salus.killaura:
                description: "A permission."
                default: false
            salus.regen:
                description: "A permission."
                default: false
            salus.forcegamemode:
                description: "A permission."
                default: false

